[package]
name = "relay_spec"
version = "0.0.1"
authors = ["Ivan Rodriguez"]
edition = "2021"

[dependencies]
juniper = "0.15.11"
juniper-compose = "0.0.3"
enum-kinds = "0.5.1"
uuid = "1.3.0"
syn = "1.0.82"
quote = "1.0.10"
relay_derive = { path = "../relay_derive" }
