[package]
name = "relay_derive"
version = "0.0.1"
authors = ["Ivan Rodriguez"]
edition = "2021"

[dependencies]
juniper = "0.15.11"
juniper-compose = "0.0.3"
enum-kinds = "0.5.1"
uuid = "1.3.0"
syn = "1.0.82"
quote = "1.0.26"
proc-macro2 = "1.0.54"

[lib]
proc-macro = true